# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

evaluate_full <- function(p, s, d) {
    .Call('StabilityR_evaluate_full', PACKAGE = 'StabilityR', p, s, d)
}

evaluate_linearised <- function(p, s, d, time) {
    .Call('StabilityR_evaluate_linearised', PACKAGE = 'StabilityR', p, s, d, time)
}

run_gen_louvain <- function(graph, nullmod, time, M) {
    .Call('StabilityR_run_gen_louvain', PACKAGE = 'StabilityR', graph, nullmod, time, M)
}

varinfo <- function(x) {
    .Call('StabilityR_varinfo', PACKAGE = 'StabilityR', x)
}

